kind: pipeline
name: parser build

steps:

- name: run tests
  image: pcp1976/pytest-3.7:1.0.7
  environment:
    REPOSITORY_KEY:
      from_secret: REPOSITORY_KEY
    ARTIFACTORY_URL:
      from_secret: ARTIFACTORY_URL
  commands:
  - pipenv run pytest --junitxml=pytest.xml
  - xsltproc -o junit.xml /opt/pytest-xunit.xsl pytest.xml
  - curl -H "X-JFrog-Art-Api:$${REPOSITORY_KEY}" -T junit.xml "$${ARTIFACTORY_URL}/artifactory/wigglybot/${DRONE_COMMIT_BRANCH}/parser/junit.xml"

- name: docker pcp1976
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: HUB_USER
    password:
      from_secret: HUB_PASS
    repo: pcp1976/parser
  when:
    branch:
      include:
      - develop
    event: push

- name: docker
  pull: true
  image: plugins/docker
  settings:
    username:
      from_secret: HUB_USER
    password:
      from_secret: HUB_PASS
    repo: wigglybot/parser
    auto_tag: true
  when:
    branch:
      include:
      - release
    event: tag

- name: upload archive
  image: pcp1976/pytest-3.7:1.0.7
  environment:
    REPOSITORY_KEY:
      from_secret: REPOSITORY_KEY
    ARTIFACTORY_URL:
      from_secret: ARTIFACTORY_URL
  commands:
  - zip -r parser.zip *
  - curl -H "X-JFrog-Art-Api:$${REPOSITORY_KEY}" -T parser.zip "$${ARTIFACTORY_URL}/artifactory/wigglybot/${DRONE_COMMIT_BRANCH}/parser/parser.zip"